apiVersion: v1
kind: Service
metadata:
  name: thermometer-2
  labels:
    app: thermometer-2
spec:
  ports:
    # 1. TCP Port for Comunication
    - name: tcp-comunication
      port: 3006
      targetPort: 3006
      protocol: TCP

    # 2. UDP Port for Discovery
    - name: udp-discovery
      port: 30000
      targetPort: 30000
      protocol: UDP
      
  selector:
    app: thermometer-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thermometer-2
  labels:
    app: thermometer-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thermometer-2
  template:
    metadata:
      labels:
        app: thermometer-2
    spec:
      containers:
        - name: thermometer-2
          image: fracarluccii/domoticasw-thermometer@sha256:c59d35f81b3dc77f5f22ec295af5ad1deba1862de51eab6fd0a8a88adff55bbc
          ports:
            - containerPort: 3006 # TCP
            - containerPort: 30000 # UDP
          env:
            - name: DEVICE_PORT
              value: "3006"
            - name: LAN_HOSTNAME
              value: "thermometer-2"
            - name: ID
              value: "thermometer-2"
          envFrom:
          - configMapRef:
              name: devices-common